[repository]
name = "Hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "058d4828b5fbf0607d8bf2824b776c6c2eabb6c7"]
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "libhyprtasking.so"
build = [
    "make all"
]
