[repository]
name = "Hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "b9039bca7d92f535ed47418cca174a2b81604f79"]
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "build/libhyprtasking.so"
build = [
    "meson setup build",
    "cd build && meson compile"
]
