[repository]
name = "Hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "472956ec0ac04be6d10ad2e7e0d293748e46a5b8"]
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "libhyprtasking.so"
build = [
    "make all"
]
