[repository]
name = "Hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "d2d4ba4c6e130e4d86920bf1306813da12f0760f"]
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "libhyprtasking.so"
build = [
    "make all"
]
