[repository]
name = "Hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "1f283c4c52b112c99118240f5a70e2e702f00d05"]
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "build/libhyprtasking.so"
build = [
    "meson setup build",
    "cd build && meson compile"
]
