[repository]
name = "Hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "ef48074e59f4bbc30fcda5bd039b4988e7f3a7fd"]
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "libhyprtasking.so"
build = [
    "make all"
]
