[repository]
name = "Hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "a69d6a7a15dd10878f7d84538795e8f14b8ccc70"]
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "build/libhyprtasking.so"
build = [
    "meson setup build",
    "cd build && meson compile"
]
