[repository]
name = "Hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "e476e3c89ed85e6a08d9fca4b7983e43897f8c1d"]
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "libhyprtasking.so"
build = [
    "make all"
]
